# BÀI TẬP VỀ NHÀ: SINGULAR VALUE DECOMPOSITION (SVD)

---

## CÂU 1: PHÂN RÃ MA TRẬN VÀ TRUY VẤN SVD

### 1.1. Chứng minh các cột của $A$ phụ thuộc tuyến tính và xác định $\operatorname{rank}(A)$

Cho ma trận:
$$
A = \begin{bmatrix} 1 & 0 & 1 \\ 0 & 1 & 1 \\ 1 & 0 & 1 \\ 0 & 1 & 1 \end{bmatrix} \in \mathbb{R}^{4 \times 3}
$$

Đặt các cột của $A$ lần lượt là:
$$
a_1 = \begin{bmatrix} 1 \\ 0 \\ 1 \\ 0 \end{bmatrix}, \quad
a_2 = \begin{bmatrix} 0 \\ 1 \\ 0 \\ 1 \end{bmatrix}, \quad
a_3 = \begin{bmatrix} 1 \\ 1 \\ 1 \\ 1 \end{bmatrix}
$$

- Ta thấy: $a_3 = a_1 + a_2$ (vì $\begin{bmatrix} 1 \\ 0 \\ 1 \\ 0 \end{bmatrix} + \begin{bmatrix} 0 \\ 1 \\ 0 \\ 1 \end{bmatrix} = \begin{bmatrix} 1 \\ 1 \\ 1 \\ 1 \end{bmatrix}$).
- Do cột 3 biểu diễn được thành tổng của cột 1 và cột 2, nên tập các cột $\{a_1, a_2, a_3\}$ phụ thuộc tuyến tính.
- Mặt khác, $a_1$ và $a_2$ độc lập tuyến tính (không phải bội số của nhau).
- Do đó, số lượng cột độc lập tuyến tính tối đại của $A$ là 2.
- Kết luận: $\operatorname{rank}(A) = 2$.

---

### 1.2. Tính $A^\top A$

Chuyển vị của $A$:
$$
A^\top = \begin{bmatrix} 1 & 0 & 1 & 0 \\ 0 & 1 & 0 & 1 \\ 1 & 1 & 1 & 1 \end{bmatrix} \in \mathbb{R}^{3 \times 4}
$$

Tính tích $A^\top A$:
$$
A^\top A = \begin{bmatrix} 1 & 0 & 1 & 0 \\ 0 & 1 & 0 & 1 \\ 1 & 1 & 1 & 1 \end{bmatrix} \begin{bmatrix} 1 & 0 & 1 \\ 0 & 1 & 1 \\ 1 & 0 & 1 \\ 0 & 1 & 1 \end{bmatrix} = \begin{bmatrix} 2 & 0 & 2 \\ 0 & 2 & 2 \\ 2 & 2 & 4 \end{bmatrix} \in \mathbb{R}^{3 \times 3}
$$

---

### 1.3 - 1.4. Tìm eigenvalues và eigenvectors trực chuẩn của $A^\top A$, sắp xếp theo thứ tự giảm dần

Phương trình đặc trưng $\det(A^\top A - \lambda I) = 0$:
$$
\begin{vmatrix} 2-\lambda & 0 & 2 \\ 0 & 2-\lambda & 2 \\ 2 & 2 & 4-\lambda \end{vmatrix} = 0
$$

Khai triển định thức:
$$
(2-\lambda) \left[ (2-\lambda)(4-\lambda) - 4 \right] + 2 \left[ 0 - 2(2-\lambda) \right] = 0
$$
$$
(2-\lambda) (\lambda^2 - 6\lambda + 8 - 4) - 4(2-\lambda) = 0
$$
$$
(2-\lambda) (\lambda^2 - 6\lambda) = 0 \implies \lambda(2-\lambda)(\lambda-6) = 0
$$

Các giá trị riêng (eigenvalues) thu được: $\lambda = 6, 2, 0$.

Sắp xếp theo thứ tự giảm dần:
$$
\lambda_1 = 6, \quad \lambda_2 = 2, \quad \lambda_3 = 0
$$

#### Tìm các vector riêng trực chuẩn (orthonormal eigenvectors) $v_1, v_2, v_3$:

1. Với $\lambda_1 = 6$:
$$
(A^\top A - 6I) v_1 = 0 \iff \begin{bmatrix} -4 & 0 & 2 \\ 0 & -4 & 2 \\ 2 & 2 & -2 \end{bmatrix} \begin{bmatrix} x \\ y \\ z \end{bmatrix} = \begin{bmatrix} 0 \\ 0 \\ 0 \end{bmatrix}
$$
Giải hệ: $-4x + 2z = 0 \implies z = 2x$, $-4y + 2z = 0 \implies z = 2y \implies x = y$.
Chọn $x = 1 \implies v_1' = \begin{bmatrix} 1 \\ 1 \\ 2 \end{bmatrix}$. Độ dài $\|v_1'\| = \sqrt{1^2+1^2+2^2} = \sqrt{6}$.
Chuẩn hóa:
$$
v_1 = \frac{1}{\sqrt{6}} \begin{bmatrix} 1 \\ 1 \\ 2 \end{bmatrix}
$$

2. Với $\lambda_2 = 2$:
$$
(A^\top A - 2I) v_2 = 0 \iff \begin{bmatrix} 0 & 0 & 2 \\ 0 & 0 & 2 \\ 2 & 2 & 2 \end{bmatrix} \begin{bmatrix} x \\ y \\ z \end{bmatrix} = \begin{bmatrix} 0 \\ 0 \\ 0 \end{bmatrix}
$$
Giải hệ: $2z = 0 \implies z = 0$, $2x + 2y + 2z = 0 \implies y = -x$.
Chọn $x = 1 \implies v_2' = \begin{bmatrix} 1 \\ -1 \\ 0 \end{bmatrix}$. Độ dài $\|v_2'\| = \sqrt{1^2+(-1)^2+0^2} = \sqrt{2}$.
Chuẩn hóa:
$$
v_2 = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ -1 \\ 0 \end{bmatrix}
$$

3. Với $\lambda_3 = 0$:
$$
(A^\top A) v_3 = 0 \iff \begin{bmatrix} 2 & 0 & 2 \\ 0 & 2 & 2 \\ 2 & 2 & 4 \end{bmatrix} \begin{bmatrix} x \\ y \\ z \end{bmatrix} = \begin{bmatrix} 0 \\ 0 \\ 0 \end{bmatrix}
$$
Giải hệ: $2x + 2z = 0 \implies x = -z$, $2y + 2z = 0 \implies y = -z$.
Chọn $z = -1 \implies v_3' = \begin{bmatrix} 1 \\ 1 \\ -1 \end{bmatrix}$. Độ dài $\|v_3'\| = \sqrt{1^2+1^2+(-1)^2} = \sqrt{3}$.
Chuẩn hóa:
$$
v_3 = \frac{1}{\sqrt{3}} \begin{bmatrix} 1 \\ 1 \\ -1 \end{bmatrix}
$$

---

### 1.5. Tính các singular values $\sigma_i = \sqrt{\lambda_i}$

$$
\sigma_1 = \sqrt{\lambda_1} = \sqrt{6}
$$
$$
\sigma_2 = \sqrt{\lambda_2} = \sqrt{2}
$$
$$
\sigma_3 = \sqrt{\lambda_3} = 0
$$

---

### 1.6. Xác định ma trận Right Singular Vectors $V$ và $V^\top$

Ma trận $V \in \mathbb{R}^{3 \times 3}$:
$$
V = \begin{bmatrix} v_1 & v_2 & v_3 \end{bmatrix} = \begin{bmatrix} \frac{1}{\sqrt{6}} & \frac{1}{\sqrt{2}} & \frac{1}{\sqrt{3}} \\ \frac{1}{\sqrt{6}} & -\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{3}} \\ \frac{2}{\sqrt{6}} & 0 & -\frac{1}{\sqrt{3}} \end{bmatrix}
$$

Do đó $V^\top \in \mathbb{R}^{3 \times 3}$:
$$
V^\top = \begin{bmatrix} \frac{1}{\sqrt{6}} & \frac{1}{\sqrt{6}} & \frac{2}{\sqrt{6}} \\ \frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}} & 0 \\ \frac{1}{\sqrt{3}} & \frac{1}{\sqrt{3}} & -\frac{1}{\sqrt{3}} \end{bmatrix}
$$

---

### 1.7. Tính các Left Singular Vectors $u_i = Av_i / \sigma_i$ với các $\sigma_i > 0$

1. Với $\sigma_1 = \sqrt{6}$:
$$
A v_1 = \begin{bmatrix} 1 & 0 & 1 \\ 0 & 1 & 1 \\ 1 & 0 & 1 \\ 0 & 1 & 1 \end{bmatrix} \begin{bmatrix} 1/\sqrt{6} \\ 1/\sqrt{6} \\ 2/\sqrt{6} \end{bmatrix} = \begin{bmatrix} 3/\sqrt{6} \\ 3/\sqrt{6} \\ 3/\sqrt{6} \\ 3/\sqrt{6} \end{bmatrix}
$$
$$
u_1 = \frac{A v_1}{\sigma_1} = \frac{1}{\sqrt{6}} \begin{bmatrix} 3/\sqrt{6} \\ 3/\sqrt{6} \\ 3/\sqrt{6} \\ 3/\sqrt{6} \end{bmatrix} = \begin{bmatrix} 1/2 \\ 1/2 \\ 1/2 \\ 1/2 \end{bmatrix}
$$

2. Với $\sigma_2 = \sqrt{2}$:
$$
A v_2 = \begin{bmatrix} 1 & 0 & 1 \\ 0 & 1 & 1 \\ 1 & 0 & 1 \\ 0 & 1 & 1 \end{bmatrix} \begin{bmatrix} 1/\sqrt{2} \\ -1/\sqrt{2} \\ 0 \end{bmatrix} = \begin{bmatrix} 1/\sqrt{2} \\ -1/\sqrt{2} \\ 1/\sqrt{2} \\ -1/\sqrt{2} \end{bmatrix}
$$
$$
u_2 = \frac{A v_2}{\sigma_2} = \frac{1}{\sqrt{2}} \begin{bmatrix} 1/\sqrt{2} \\ -1/\sqrt{2} \\ 1/\sqrt{2} \\ -1/\sqrt{2} \end{bmatrix} = \begin{bmatrix} 1/2 \\ -1/2 \\ 1/2 \\ -1/2 \end{bmatrix}
$$

---

### 1.8. Bổ sung các vector trực chuẩn còn thiếu để viết Full SVD ($A = U \Sigma V^\top$)

Ta cần bổ sung 2 vector trực chuẩn $u_3, u_4 \in \mathbb{R}^4$ sao cho $\{u_1, u_2, u_3, u_4\}$ tạo thành cơ sở trực chuẩn cho $\mathbb{R}^4$.

Gọi $u = \begin{bmatrix} a \\ b \\ c \\ d \end{bmatrix}$. Điều kiện trực giao với $u_1, u_2$:
- $u \cdot u_1 = 0 \iff \frac{1}{2}(a + b + c + d) = 0 \implies a + b + c + d = 0$
- $u \cdot u_2 = 0 \iff \frac{1}{2}(a - b + c - d) = 0 \implies a - b + c - d = 0$

Cộng và trừ hai phương trình:
$$
(a+c) = 0 \implies c = -a
$$
$$
(b+d) = 0 \implies d = -b
$$

Chọn hai vector trực chuẩn thỏa mãn:
- Chọn $a = 1/\sqrt{2}, b = 0 \implies u_3 = \begin{bmatrix} 1/\sqrt{2} \\ 0 \\ -1/\sqrt{2} \\ 0 \end{bmatrix}$
- Chọn $a = 0, b = 1/\sqrt{2} \implies u_4 = \begin{bmatrix} 0 \\ 1/\sqrt{2} \\ 0 \\ -1/\sqrt{2} \end{bmatrix}$

Kiểm tra: $\|u_3\| = 1, \|u_4\| = 1$ và $u_3 \cdot u_4 = 0$.

#### Ma trận Full SVD:
$$
U = \begin{bmatrix} 1/2 & 1/2 & 1/\sqrt{2} & 0 \\ 1/2 & -1/2 & 0 & 1/\sqrt{2} \\ 1/2 & 1/2 & -1/\sqrt{2} & 0 \\ 1/2 & -1/2 & 0 & -1/\sqrt{2} \end{bmatrix} \in \mathbb{R}^{4 \times 4}
$$
$$
\Sigma = \begin{bmatrix} \sqrt{6} & 0 & 0 \\ 0 & \sqrt{2} & 0 \\ 0 & 0 & 0 \\ 0 & 0 & 0 \end{bmatrix} \in \mathbb{R}^{4 \times 3}
$$
$$
V^\top = \begin{bmatrix} \frac{1}{\sqrt{6}} & \frac{1}{\sqrt{6}} & \frac{2}{\sqrt{6}} \\ \frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}} & 0 \\ \frac{1}{\sqrt{3}} & \frac{1}{\sqrt{3}} & -\frac{1}{\sqrt{3}} \end{bmatrix} \in \mathbb{R}^{3 \times 3}
$$

Biểu diễn Full SVD:
$$
A = U \Sigma V^\top
$$

---

### 1.9 - 1.10. Viết Reduced SVD và ghi rõ kích thước các ma trận

Trong Reduced SVD, ta chỉ giữ lại $r = \operatorname{rank}(A) = 2$ thành phần ứng với các giá trị singular khác 0 ($\sigma_1, \sigma_2$):

$$
U_r = \begin{bmatrix} u_1 & u_2 \end{bmatrix} = \begin{bmatrix} 1/2 & 1/2 \\ 1/2 & -1/2 \\ 1/2 & 1/2 \\ 1/2 & -1/2 \end{bmatrix} \in \mathbb{R}^{4 \times 2}
$$

$$
\Sigma_r = \begin{bmatrix} \sigma_1 & 0 \\ 0 & \sigma_2 \end{bmatrix} = \begin{bmatrix} \sqrt{6} & 0 \\ 0 & \sqrt{2} \end{bmatrix} \in \mathbb{R}^{2 \times 2}
$$

$$
V_r^\top = \begin{bmatrix} v_1^\top \\ v_2^\top \end{bmatrix} = \begin{bmatrix} \frac{1}{\sqrt{6}} & \frac{1}{\sqrt{6}} & \frac{2}{\sqrt{6}} \\ \frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}} & 0 \end{bmatrix} \in \mathbb{R}^{2 \times 3}
$$

Kích thước của các ma trận trong Reduced SVD:
- $U_r \in \mathbb{R}^{4 \times 2}$
- $\Sigma_r \in \mathbb{R}^{2 \times 2}$
- $V_r^\top \in \mathbb{R}^{2 \times 3}$

Biểu diễn Reduced SVD:
$$
A = U_r \Sigma_r V_r^\top
$$

---

### 1.11. Kiểm tra $U^\top U = I$, $V^\top V = I$ và $U \Sigma V^\top = A$

1. $U^\top U = I_4$:
   Các cột $u_1, u_2, u_3, u_4$ hình thành một hệ trực chuẩn trong \mathbb{R}^4, do đó $U$ là ma trận trực giao (orthogonal matrix) thỏa mãn $U^\top U = I_4$.

2. $V^\top V = I_3$:
   Các cột $v_1, v_2, v_3$ hình thành một hệ trực chuẩn trong \mathbb{R}^3, do đó $V$ là ma trận trực giao thỏa mãn $V^\top V = I_3$.

3. Tái tạo ma trận $A$:
   $$
   U_r \Sigma_r V_r^\top = \begin{bmatrix} 1/2 & 1/2 \\ 1/2 & -1/2 \\ 1/2 & 1/2 \\ 1/2 & -1/2 \end{bmatrix} \begin{bmatrix} \sqrt{6} & 0 \\ 0 & \sqrt{2} \end{bmatrix} \begin{bmatrix} \frac{1}{\sqrt{6}} & \frac{1}{\sqrt{6}} & \frac{2}{\sqrt{6}} \\ \frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}} & 0 \end{bmatrix}
   $$
   $$
   = \begin{bmatrix} \frac{\sqrt{6}}{2} & \frac{\sqrt{2}}{2} \\ \frac{\sqrt{6}}{2} & -\frac{\sqrt{2}}{2} \\ \frac{\sqrt{6}}{2} & \frac{\sqrt{2}}{2} \\ \frac{\sqrt{6}}{2} & -\frac{\sqrt{2}}{2} \end{bmatrix} \begin{bmatrix} \frac{1}{\sqrt{6}} & \frac{1}{\sqrt{6}} & \frac{2}{\sqrt{6}} \\ \frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}} & 0 \end{bmatrix} = \begin{bmatrix} 1 & 0 & 1 \\ 0 & 1 & 1 \\ 1 & 0 & 1 \\ 0 & 1 & 1 \end{bmatrix} = A
   $$

---

### 1.12. Giải thích lý thuyết

1. **Vì sao có một singular value bằng 0?**
   - Hạng của ma trận $A$ bằng số lượng singular values lớn hơn 0 của nó. Do $\operatorname{rank}(A) = 2$ và ma trận $A$ có kích thước $4 \times 3$ với tổng cộng $\min(4,3) = 3$ giá trị singular, nên chắc chắn có $3 - 2 = 1$ giá trị singular bằng 0 ($\sigma_3 = 0$).

2. **Singular vector tương ứng với singular value bằng 0 liên hệ thế nào với null space của $A$?**
   - Vector $v_3$ ứng với $\sigma_3 = 0$ chính là vector thuộc không gian nghiệm (Null space / Kernel) của ma trận $A$, tức là thỏa mãn $A v_3 = 0$.

3. **Vì sao Reduced SVD vẫn tái tạo chính xác $A$?**
   - Trong biểu diễn Full SVD $A = \sum_{i=1}^3 \sigma_i u_i v_i^\top$, thành phần thứ 3 là $\sigma_3 u_3 v_3^\top = 0 \cdot u_3 v_3^\top = 0$. Do đó, thành phần này không đóng góp vào giá trị của ma trận $A$. Vì vậy, Reduced SVD loại bỏ thành phần bằng 0 này mà vẫn thu được kết quả hoàn toàn chính xác $A = U_r \Sigma_r V_r^\top$.


In [1]:
import numpy as np

A = np.array([
    [1, 0, 1],
    [0, 1, 1],
    [1, 0, 1],
    [0, 1, 1]
], dtype=float)

rank_A = np.linalg.matrix_rank(A)
print("Rank của A:", rank_A)

AtA = A.T @ A
print("Ma trận A^T A:\n", AtA)

evals, evecs = np.linalg.eigh(AtA)
idx = np.argsort(evals)[::-1]
evals = evals[idx]
evecs = evecs[:, idx]

print("Eigenvalues sắp xếp giảm dần:", evals)

singular_values = np.sqrt(np.maximum(evals, 0))
print("Singular values:", singular_values)

U, S, Vt = np.linalg.svd(A, full_matrices=True)
print("U (Full SVD):\n", np.round(U, 4))
print("S (Singular values từ np.linalg.svd):", np.round(S, 4))
print("V^T (Full SVD):\n", np.round(Vt, 4))

U_r, S_r, Vt_r = np.linalg.svd(A, full_matrices=False)
A_reconstructed = U_r @ np.diag(S_r) @ Vt_r
print("Khôi phục ma trận A từ Reduced SVD:\n", np.round(A_reconstructed, 4))
print("Sai số khôi phục (Frobenius norm):", np.linalg.norm(A - A_reconstructed))


Rank của A: 2
Ma trận A^T A:
 [[2. 0. 2.]
 [0. 2. 2.]
 [2. 2. 4.]]
Eigenvalues sắp xếp giảm dần: [6.00000000e+00 2.00000000e+00 1.99931645e-16]
Singular values: [2.44948974e+00 1.41421356e+00 1.41397187e-08]
U (Full SVD):
 [[-0.5     0.5    -0.7071  0.    ]
 [-0.5    -0.5     0.     -0.7071]
 [-0.5     0.5     0.7071  0.    ]
 [-0.5    -0.5     0.      0.7071]]
S (Singular values từ np.linalg.svd): [2.4495 1.4142 0.    ]
V^T (Full SVD):
 [[-0.4082 -0.4082 -0.8165]
 [ 0.7071 -0.7071 -0.    ]
 [ 0.5774  0.5774 -0.5774]]
Khôi phục ma trận A từ Reduced SVD:
 [[ 1.  0.  1.]
 [-0.  1.  1.]
 [ 1.  0.  1.]
 [-0.  1.  1.]]
Sai số khôi phục (Frobenius norm): 1.1796450345895336e-15


---

## CÂU 2: CHỌN $k$ CHO TRUNCATED SVD BẰNG TỶ LỆ NĂNG LƯỢNG

Cho các giá trị singular của ma trận dữ liệu $X$:
$$
\sigma_1 = 12, \quad \sigma_2 = 5, \quad \sigma_3 = 3, \quad \sigma_4 = 1
$$

Ma trận xấp xỉ hạng $k$:
$$
X_k = \sum_{i=1}^{k} \sigma_i u_i v_i^\top
$$

---

### 2.1. Xác định rank của $X$

- Do cả 4 giá trị singular $\sigma_1, \sigma_2, \sigma_3, \sigma_4$ đều lớn hơn 0, nên số lượng giá trị singular khác 0 của $X$ là 4.
- Kết luận: $\operatorname{rank}(X) = 4$.

---

### 2.2. Tính tổng năng lượng $E_{\text{total}}$

Tổng năng lượng của ma trận $X$ được tính bằng tổng bình phương của tất cả các giá trị singular:
$$
E_{\text{total}} = \sum_{i=1}^{4} \sigma_i^2 = \sigma_1^2 + \sigma_2^2 + \sigma_3^2 + \sigma_4^2
$$
$$
E_{\text{total}} = 12^2 + 5^2 + 3^2 + 1^2 = 144 + 25 + 9 + 1 = 179
$$

---

### 2.3 - 2.4. Tính tỷ lệ năng lượng $R(k)$ và hoàn thành Bảng 1

Tỷ lệ năng lượng giữ lại với $k$ thành phần:
$$
R(k) = \frac{\sum_{i=1}^{k} \sigma_i^2}{E_{\text{total}}} = \frac{\sum_{i=1}^{k} \sigma_i^2}{179}
$$

1. Khi $k = 1$:
   - Năng lượng giữ lại: $\sigma_1^2 = 144$
   - $R(1) = \frac{144}{179} \approx 0.804469 \approx 80.45\%$

2. Khi $k = 2$:
   - Năng lượng giữ lại: $\sigma_1^2 + \sigma_2^2 = 144 + 25 = 169$
   - $R(2) = \frac{169}{179} \approx 0.944134 \approx 94.41\%$

3. Khi $k = 3$:
   - Năng lượng giữ lại: $\sigma_1^2 + \sigma_2^2 + \sigma_3^2 = 169 + 9 = 178$
   - $R(3) = \frac{178}{179} \approx 0.994413 \approx 99.44\%$

4. Khi $k = 4$:
   - Năng lượng giữ lại: $\sigma_1^2 + \sigma_2^2 + \sigma_3^2 + \sigma_4^2 = 178 + 1 = 179$
   - $R(4) = \frac{179}{179} = 1.0000 = 100.00\%$

#### Bảng 1: Năng lượng giữ lại và Tỷ lệ $R(k)$

| $k$ | Năng lượng giữ lại $\sum_{i=1}^{k}\sigma_i^2$ | Tỷ lệ $R(k)$ |
|---:|---:|---:|
| 1 | 144 | 80.45% (0.8045) |
| 2 | 169 | 94.41% (0.9441) |
| 3 | 178 | 99.44% (0.9944) |
| 4 | 179 | 100.00% (1.0000) |

---

### 2.5. Tìm $k$ nhỏ nhất theo các ngưỡng năng lượng

- **Ít nhất 80% năng lượng ($R(k) \ge 0.80$)**: $k = 1$ (do $R(1) = 80.45\% \ge 80\%$)
- **Ít nhất 90% năng lượng ($R(k) \ge 0.90$)**: $k = 2$ (do $R(2) = 94.41\% \ge 90\%$)
- **Ít nhất 95% năng lượng ($R(k) \ge 0.95$)**: $k = 3$ (do $R(3) = 99.44\% \ge 95\%$)
- **Ít nhất 99% năng lượng ($R(k) \ge 0.99$)**: $k = 3$ (do $R(3) = 99.44\% \ge 99\%$)

---

### 2.6 - 2.7. Tính sai số xấp xỉ Frobenius norm $\|X - X_k\|_F$ và hoàn thành Bảng 2

Sai số xấp xỉ ma trận được tính theo công thức:
$$
\|X - X_k\|_F = \sqrt{\sum_{i=k+1}^{4} \sigma_i^2}
$$

1. Khi $k = 1$:
   $$
   \|X - X_1\|_F = \sqrt{\sigma_2^2 + \sigma_3^2 + \sigma_4^2} = \sqrt{25 + 9 + 1} = \sqrt{35} \approx 5.9161
   $$

2. Khi $k = 2$:
   $$
   \|X - X_2\|_F = \sqrt{\sigma_3^2 + \sigma_4^2} = \sqrt{9 + 1} = \sqrt{10} \approx 3.1623
   $$

3. Khi $k = 3$:
   $$
   \|X - X_3\|_F = \sqrt{\sigma_4^2} = \sqrt{1} = 1.0000
   $$

#### Bảng 2: Tỷ lệ $R(k)$ và Sai số $\|X - X_k\|_F$

| $k$ | $R(k)$ | $\|X-X_k\|_F$ |
|---:|---:|---:|
| 1 | 80.45% (0.8045) | $\sqrt{35} \approx 5.9161$ |
| 2 | 94.41% (0.9441) | $\sqrt{10} \approx 3.1623$ |
| 3 | 99.44% (0.9944) | $1.0000$ |

---

### 2.8. Chọn $k$ phù hợp khi $\sigma_4$ chủ yếu biểu diễn nhiễu

- Nếu $\sigma_4 = 1$ chủ yếu chứa nhiễu (noise), ta nên loại bỏ thành phần này và chọn **$k = 3$**.
- **Giải thích**:
  - Chọn $k = 3$ giúp loại bỏ hoàn toàn nhiễu $\sigma_4 = 1$ nhưng vẫn giữ lại tới $99.44\%$ năng lượng thông tin thực sự của ma trận dữ liệu.
  - Sai số xấp xỉ lúc này $\|X - X_3\|_F = 1.0$, bằng đúng độ lớn của thành phần nhiễu bị triệt tiêu.

---

### 2.9. Trả lời các câu hỏi lý thuyết

1. **Vì sao singular values phải được sắp xếp giảm dần?**
   - Việc sắp xếp các giá trị singular giảm dần ($\sigma_1 \ge \sigma_2 \ge \dots \ge \sigma_r$) đảm bảo rằng những thành phần đứng đầu mang lượng thông tin (năng lượng) lớn nhất của ma trận.
   - Theo định lý Eckart-Young-Mirsky, ma trận xấp xỉ hạng $k$ thu được bằng cách giữ lại $k$ giá trị singular đầu tiên sẽ là ma trận xấp xỉ tối ưu nhất, cho sai số Frobenius norm $\|X - X_k\|_F$ là **nhỏ nhất** có thể đối với mọi ma trận hạng $k$.

2. **Giữ càng nhiều singular values có phải lúc nào cũng tốt hơn không?**
   - **Không.** Mặc dù giữ nhiều giá trị singular làm giảm sai số xấp xỉ so với dữ liệu gốc, nhưng nó có 2 nhược điểm lớn:
     1. **Lưu giữ nhiễu (Noise overfitting)**: Các giá trị singular nhỏ thường đại diện cho nhiễu ngẫu nhiên hoặc biến động không mong muốn.
     2. **Tốn tài nguyên tính toán và lưu trữ**: Không phát huy được hiệu quả nén dữ liệu và giảm chiều (dimensionality reduction), khiến các mô hình học máy phía sau gặp rắc rối với hiện tượng "curse of dimensionality".

3. **Sự đánh đổi (trade-off) giữa tỷ lệ năng lượng và mức độ nén dữ liệu là gì?**
   - **Khi chọn $k$ nhỏ**: Mức độ nén cao (dữ liệu gọn nhẹ, loại bỏ nhiễu tốt, tính toán nhanh), nhưng tỷ lệ năng lượng $R(k)$ thấp hơn, làm tăng sai số khôi phục $\|X - X_k\|_F$.
   - **Khi chọn $k$ lớn**: Tỷ lệ năng lượng $R(k)$ cao (khôi phục chính xác thông tin ban đầu, sai số nhỏ), nhưng mức độ nén kém và có nguy cơ lưu giữ cả nhiễu.


In [2]:
import numpy as np
import pandas as pd

sigma = np.array([12, 5, 3, 1], dtype=float)

rank_X = len(sigma)
print("Rank của X:", rank_X)

energy = sigma**2
E_total = np.sum(energy)
print("Tổng năng lượng E_total:", E_total)

cum_energy = np.cumsum(energy)
R_k = cum_energy / E_total

table1_data = {
    "k": [1, 2, 3, 4],
    "Năng lượng giữ lại": cum_energy,
    "Tỷ lệ R(k)": [f"{r*100:.2f}% ({r:.4f})" for r in R_k]
}
df_table1 = pd.DataFrame(table1_data)
print("\n--- BẢNG 1 ---")
print(df_table1.to_string(index=False))

thresholds = [0.80, 0.90, 0.95, 0.99]
for t in thresholds:
    k_min = np.argmax(R_k >= t) + 1
    print(f"k nhỏ nhất để giữ ít nhất {int(t*100)}% năng lượng là: k = {k_min} (R({k_min}) = {R_k[k_min-1]*100:.2f}%)")

error_frobenius = [np.sqrt(np.sum(energy[k:])) for k in range(1, 4)]

table2_data = {
    "k": [1, 2, 3],
    "R(k)": [f"{R_k[k-1]*100:.2f}% ({R_k[k-1]:.4f})" for k in range(1, 4)],
    "||X - X_k||_F": [f"{err:.4f}" for err in error_frobenius]
}
df_table2 = pd.DataFrame(table2_data)
print("\n--- BẢNG 2 ---")
print(df_table2.to_string(index=False))


Rank của X: 4
Tổng năng lượng E_total: 179.0

--- BẢNG 1 ---
 k  Năng lượng giữ lại       Tỷ lệ R(k)
 1               144.0  80.45% (0.8045)
 2               169.0  94.41% (0.9441)
 3               178.0  99.44% (0.9944)
 4               179.0 100.00% (1.0000)
k nhỏ nhất để giữ ít nhất 80% năng lượng là: k = 1 (R(1) = 80.45%)
k nhỏ nhất để giữ ít nhất 90% năng lượng là: k = 2 (R(2) = 94.41%)
k nhỏ nhất để giữ ít nhất 95% năng lượng là: k = 3 (R(3) = 99.44%)
k nhỏ nhất để giữ ít nhất 99% năng lượng là: k = 3 (R(3) = 99.44%)

--- BẢNG 2 ---
 k            R(k) ||X - X_k||_F
 1 80.45% (0.8045)        5.9161
 2 94.41% (0.9441)        3.1623
 3 99.44% (0.9944)        1.0000
